cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name='add'),
    path('remove/<int:product_id>/', remove, name='remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('shop.urls')),
    path('cart', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
   <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            crossorigin="anonymous">
    </script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <title>
    {% block title%}
        OnlineShop
    {% endblock %}
    </title>

    {% block script %}



    {% endblock %}

    {% block style %}
    {% endblock %}
</head>
<body>

<!--navebar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Django Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav justify-content-end">
        <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link btn btn-outline-success">Welcome, {{ user.username }}</a>
            {% else %}
            <a class="nav-link btn btn-outline-success">Welcome, 방문자님 </a>
            {% endif %}
            </a>
        </li>
        &nbsp;&nbsp;
        <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link btn btn-outline-success" href="{% url 'account_logout' %}">Logout</a>
            {% else %}
            <a class="nav-link btn btn-outline-success" href="{% url 'account_login' %}">Login</a>
            {% endif %}
        </li>
        &nbsp;&nbsp;
        <li class="nav-item">
            <a class="nav-link btn btn-outline-success" href="{% url 'cart:detail' %}">Cart
                {% if cart|length > 0 %}
                    ${{ cart.get_total_price }} with {{cart|length}} items
                {% else %}
                    : Empty
                {% endif %}
            </a>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
           <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
           <button class="btn btn-outline-success my-2 my-sm-0" onclick="alert(1);" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>


</body>
</html>